# Generated by Django 4.1.3 on 2023-01-06 19:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mipscode', '0004_alter_repositorio_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='Biografia do Usuário')),
                ('avatar', models.ImageField(default='avatar/default.jpg', upload_to='avatar')),
                ('user_type', models.CharField(choices=[('1', 'Admin'), ('2', 'Student'), ('3', 'Teacher')], default='2', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide_theme', models.CharField(choices=[('1', 'Dark'), ('2', 'Light')], default='1', max_length=1)),
                ('language', models.CharField(choices=[('1', 'Português'), ('2', 'Inglês')], default='1', max_length=1)),
                ('email_notification', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mipscode.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 19, 35, 19, 224976, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 19, 35, 19, 222979, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mipscode.profile'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mipscode.profile'),
        ),
        migrations.DeleteModel(
            name='UserNew',
        ),
    ]
