# Generated by Django 4.1.3 on 2023-01-06 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipscode', '0005_profile_profilesettings_alter_repositorio_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 19, 51, 27, 306144, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 19, 51, 27, 303145, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
    ]
