# Generated by Django 4.1.3 on 2022-12-28 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipscode', '0009_alter_user_managers_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 18, 58, 58, 673465, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 18, 58, 58, 672461, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
    ]
