# Generated by Django 4.1.3 on 2022-12-28 20:45

import datetime
from django.db import migrations, models
import mipscode.models


class Migration(migrations.Migration):

    dependencies = [
        ('mipscode', '0010_alter_project_created_at_alter_tutorial_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.JSONField(default=mipscode.models.Project.content_default, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 20, 45, 0, 169736, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 20, 45, 0, 168703, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
    ]
