# Generated by Django 4.1.3 on 2022-12-29 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipscode', '0011_alter_project_content_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 15, 7, 38, 78259, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 15, 7, 38, 77259, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
    ]
